### crawler/start
POST http://localhost:8080/crawler/start
Content-Type: application/json

{
  "urls": [
    "https://ru.wikipedia.org/wiki/Java",
    "https://habr.com/ru/companies/ru_mts/articles",
    "https://history.eco"
  ],
  "maxDepth": 3
}

### searcher/match-rows
GET http://localhost:8080/searcher/match-rows?query=языки программирования

### searcher/sorted-list
GET http://localhost:8080/searcher/sorted-list?query=языки программирования

### searcher/page-rank
POST http://localhost:8080/searcher/page-rank
Content-Type: application/json

{
  "iterations": 4
}

### searcher/page-rank-scores
GET http://localhost:8080/searcher/page-rank-scores?query=древняя история

### searcher/highlight
POST http://localhost:8080/searcher/highlight
Content-Type: application/json

{
  "query": "языки программирования"
}