POST http://localhost:8080/crawler/start
Content-Type: application/json

{
  "urls": [
    "https://ru.wikipedia.org/wiki/Java",
    "https://habr.com/ru/companies/spring_aio/news/847460/",
    "https://history.eco/category/drevnie-ruiny/"
  ],
  "maxDepth": 2
}

